# Generated by Django 6.1.2 on 2026-10-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_sale_customer_name_sale_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
